from __future__ import annotations

from datetime import date, datetime
from typing import Any, Protocol
from uuid import UUID

from ..models import ComparisonItem, NormalizedMarketObservation


class MarketRepository(Protocol):
    async def resolve_crop(self, canonical_code: str) -> UUID | None: ...
    async def resolve_variety(self, canonical_name: str) -> tuple[UUID, UUID] | None: ...
    async def validate_crop_variety(self, crop_id: UUID, variety_id: UUID) -> bool: ...
    async def resolve_mandi(self, provider_name: str, external_id: str) -> UUID | None: ...
    async def upsert_provider_mandi(
        self, provider_name: str, external_id: str, name: str, district: str | None, state: str
    ) -> UUID: ...
    async def insert_observation(
        self, observation: NormalizedMarketObservation
    ) -> tuple[NormalizedMarketObservation, bool]: ...
    async def latest_genuine_observation(
        self, subject: dict[str, Any], as_of: datetime
    ) -> NormalizedMarketObservation | None: ...
    async def latest_demo_observation(
        self, subject: dict[str, Any], dataset_id: str, as_of: datetime
    ) -> NormalizedMarketObservation | None: ...
    async def create_history(
        self, observation: NormalizedMarketObservation, price_date: date, version: str
    ) -> UUID: ...
    async def market_history(
        self, crop_id: UUID, variety_id: UUID | None, mandi_ids: list[UUID], limit: int
    ) -> list[dict[str, Any]]: ...
    async def comparison(
        self, crop_id: UUID, variety_id: UUID | None, mandi_ids: list[UUID], as_of: datetime
    ) -> list[ComparisonItem]: ...
