create table public.buyer_demands (
  id uuid primary key default gen_random_uuid(),
  buyer_profile_id uuid references public.buyer_profiles(profile_id) on delete restrict,
  fpo_id uuid references public.fpos(id) on delete restrict,
  crop_id uuid not null references public.crops(id) on delete restrict,
  variety_id uuid references public.crop_varieties(id) on delete restrict,
  minimum_quantity numeric(14,3) not null check (minimum_quantity > 0),
  maximum_quantity numeric(14,3) not null check (maximum_quantity >= minimum_quantity),
  fulfilled_quantity numeric(14,3) not null default 0 check (fulfilled_quantity >= 0 and fulfilled_quantity <= maximum_quantity),
  unit text not null default 'kg',
  quality_requirements jsonb not null default '{}'::jsonb,
  delivery_from date not null,
  delivery_until date not null,
  delivery_district text,
  delivery_state text not null,
  indicative_price numeric(14,2) check (indicative_price is null or indicative_price >= 0),
  currency char(3) not null default 'INR',
  status public.demand_status not null default 'DRAFT',
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check ((buyer_profile_id is not null)::integer + (fpo_id is not null)::integer = 1),
  check (delivery_until >= delivery_from)
);

create table public.offers (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.produce_listings(id) on delete restrict,
  demand_id uuid references public.buyer_demands(id) on delete restrict,
  buyer_profile_id uuid references public.buyer_profiles(profile_id) on delete restrict,
  fpo_id uuid references public.fpos(id) on delete restrict,
  offered_quantity numeric(14,3) not null check (offered_quantity > 0),
  unit text not null default 'kg',
  unit_price numeric(14,2) not null check (unit_price >= 0),
  currency char(3) not null default 'INR',
  delivery_terms text not null,
  expires_at timestamptz not null,
  status public.offer_status not null default 'PENDING',
  idempotency_key text,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((buyer_profile_id is not null)::integer + (fpo_id is not null)::integer = 1)
);
