create table public.transport_providers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_phone text,
  service_geography jsonb not null default '{}'::jsonb,
  vehicle_metadata jsonb not null default '{}'::jsonb,
  capacity_kg numeric(14,3) check (capacity_kg is null or capacity_kg > 0),
  verification_status public.verification_status not null default 'UNVERIFIED',
  status public.record_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.warehouses (
  id uuid primary key default gen_random_uuid(),
  owner_profile_id uuid references public.profiles(id) on delete restrict,
  name text not null,
  district text,
  state text not null,
  capacity numeric(14,3) not null check (capacity > 0),
  capacity_unit text not null default 'kg',
  crop_support jsonb not null default '[]'::jsonb,
  rate_metadata jsonb not null default '{}'::jsonb,
  verification_status public.verification_status not null default 'UNVERIFIED',
  status public.record_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.logistics_quotes (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.produce_listings(id) on delete restrict,
  demand_id uuid references public.buyer_demands(id) on delete restrict,
  transport_provider_id uuid references public.transport_providers(id) on delete set null,
  warehouse_id uuid references public.warehouses(id) on delete set null,
  transportation_cost numeric(14,2) not null default 0 check (transportation_cost >= 0),
  storage_cost numeric(14,2) not null default 0 check (storage_cost >= 0),
  handling_cost numeric(14,2) not null default 0 check (handling_cost >= 0),
  other_applicable_cost numeric(14,2) not null default 0 check (other_applicable_cost >= 0),
  total_applicable_cost numeric(14,2) not null check (total_applicable_cost >= 0),
  currency char(3) not null default 'INR',
  distance_km numeric(12,3) check (distance_km is null or distance_km >= 0),
  assumptions jsonb not null default '{}'::jsonb,
  source_name text not null,
  data_mode public.data_mode not null,
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  dataset_id text,
  source_version text,
  checksum text,
  calculated_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (total_applicable_cost = transportation_cost + storage_cost + handling_cost + other_applicable_cost),
  check (expires_at > calculated_at)
);

create table public.recommendations (
  id uuid primary key default gen_random_uuid(),
  farmer_profile_id uuid not null references public.farmer_profiles(profile_id) on delete restrict,
  listing_id uuid not null references public.produce_listings(id) on delete restrict,
  candidate_buyer_profile_id uuid references public.buyer_profiles(profile_id) on delete restrict,
  candidate_fpo_id uuid references public.fpos(id) on delete restrict,
  candidate_mandi_id uuid references public.mandis(id) on delete restrict,
  demand_id uuid references public.buyer_demands(id) on delete restrict,
  logistics_quote_id uuid references public.logistics_quotes(id) on delete set null,
  estimated_quantity_kg numeric(14,3) not null check (estimated_quantity_kg > 0),
  estimated_unit_price_per_kg numeric(14,2) not null check (estimated_unit_price_per_kg >= 0),
  estimated_gross_selling_value numeric(14,2) not null check (estimated_gross_selling_value >= 0),
  estimated_transportation_cost numeric(14,2) not null default 0 check (estimated_transportation_cost >= 0),
  estimated_storage_cost numeric(14,2) not null default 0 check (estimated_storage_cost >= 0),
  estimated_handling_cost numeric(14,2) not null default 0 check (estimated_handling_cost >= 0),
  estimated_other_applicable_cost numeric(14,2) not null default 0 check (estimated_other_applicable_cost >= 0),
  estimated_total_applicable_cost numeric(14,2) not null check (estimated_total_applicable_cost >= 0),
  estimated_net_farmer_realization numeric(14,2) not null,
  currency char(3) not null default 'INR',
  rank integer not null check (rank > 0),
  sell_wait text check (sell_wait in ('SELL_NOW','WAIT','INSUFFICIENT_DATA')),
  explanation_facts jsonb not null default '[]'::jsonb,
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  data_mode public.data_mode not null,
  source_name text not null,
  dataset_id text,
  engine_version text not null,
  input_metadata jsonb not null default '{}'::jsonb,
  calculated_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check ((candidate_buyer_profile_id is not null)::integer + (candidate_fpo_id is not null)::integer + (candidate_mandi_id is not null)::integer = 1),
  check (estimated_total_applicable_cost = estimated_transportation_cost + estimated_storage_cost + estimated_handling_cost + estimated_other_applicable_cost),
  check (estimated_net_farmer_realization = estimated_gross_selling_value - estimated_total_applicable_cost),
  check (expires_at > calculated_at),
  unique (listing_id, engine_version, calculated_at, rank)
);

